config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/auth/github/callback', to: 'sessions#create'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'
  get '/signup', to: 'users#new'
  post '/signup', to: "users#create"

  root to: "application#home"

  # admin ----------------------------------------

  get '/admin/home', to: "application#admin_home"

  scope module: 'admin' do
  get '/admin/profile/:id', to: 'users#profile'
  patch '/admin/profile/:id', to: 'users#profile_form_handler'
  get '/admin/profile/:id/:edit', to: 'users#profile'
  get '/admin/profile/:id/:edit/:show_form', to: 'users#profile'
  end

  namespace :admin do
    resources :projects

    resources :projects, only: [:show] do
      resources :segments, only: [:show, :new, :create, :edit, :update, :destroy]
    end

    resources :segments, only: [:show] do
      resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy]
    end

    resources :teams

    resources :teams, only: [:show] do
      resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
    end

    resources :project_comments
    resources :segment_comments
    resources :task_comments
end

# Team Member ----------------------------------------

resources :projects, only: [:index, :show]

    resources :projects, only: [:show] do
      resources :segments, only: [:show]
    end

    resources :segments, only: [:show] do
      resources :tasks, only: [:show, :edit, :update]
    end

    resources :teams, only: [:index]

    resources :teams, only: [:show] do
      resources :users, only: [:show]
    end

    resources :tasks, only: [:index, :edit, :update]

    resources :project_comments
    resources :segment_comments
    resources :task_comments

  get '/profile/:id', to: 'users#profile'
  patch '/profile/:id', to: 'users#profile_form_handler'
  get '/profile/:id/:edit', to: 'users#profile'
  get '/profile/:id/:edit/:show_form', to: 'users#profile'

  # Team Leader ----------------------------------------

  get '/team-leader/home', to: "application#team_leader_home"
  
  scope module: 'team_leader' do
    get '/team_leader/profile/:id', to: 'users#profile'
    patch '/team_leader/profile/:id', to: 'users#profile_form_handler'
    get '/team_leader/profile/:id/:edit', to: 'users#profile'
    get '/team_leader/profile/:id/:edit/:show_form', to: 'users#profile'
    end
  
    namespace :team_leader do
      resources :projects, only: [:index, :show] do
        resources :segments, only: [:show, :edit, :update]
      end
  
      resources :segments, only: [:show] do
        resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy]
      end
      resources :teams, only: [:index]
    
      resources :teams, only: [:show] do
        resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
      end
  
      resources :project_comments
      resources :segment_comments
      resources :task_comments
  end

  # match must be last route

  match '*path', to: "application#notfound", via: [:get, :post]

  # Which routes need to be namespaced??

  # Admin Routes:

  #  All routes should be accessable to admin



  # Team Leader Routes:

  # Team leaders can only create tasks, create users, mark tasks and segments completed


  # Team Member Routes:

  # Team members can only edit their profile, mark tasks as completed, and comment.

  # routes that edit 
end

app/controllers/admin/tasks_controller.rb
class Admin::TasksController < ApplicationController
    before_action :current_user, :company, :admin?
    layout "admin_layout"
    
    def index
    end
    
    def new
        @task = @segment.tasks.build
    end

    def create
        @segment = Segment.find_by(id: params[:task][:segment_id])
        @task = @segment.tasks.build(task_params)
        assign_existing_user
        if @task.save
            redirect_to admin_segment_path(@segment)
        else
            render 'admin/segments/show'
        end
    end

    def show
        @task = Task.find_by(id: params[:id])
        @segment = @task.segment
    end

    def edit
        @task = Task.find_by(id: params[:id])
        @segment = @task.segment
        @task.assigned_user.nil? ? @user=(User.new) : @user=(@task.assigned_user)
        @user.assigned_position.nil? ? @position=(Position.new) : @position=(@user.assigned_position)
        if params[:show_user_form]
            @show_user_form = params[:show_user_form]
        end
    end

    def update
        @task = Task.find_by(id: params[:id])
        if @task.update(task_params)
            redirect_to admin_segment_task_path(@task)
        else
            render :edit
        end
    end

    def destroy
        @task = Task.find_by(id: params[:id])
        @segment = @task.segment
        @task.destroy
        redirect_to admin_segment_path(@segment)
    end

    private

    def task_params
        params.require(:task).permit(:title, :deadline, :description, :segment_id, :position_id, :completed,
        user_attributes: [
            :first_name,
            :last_name,
            :email,
            :password,
            :password_confirmation,
            :privilege,
            :user_param_value
        ],
        position_attributes: [
            :title,
            :description,
            :user_id
        ]).with_defaults(user_id: current_user.id)
    end

    def assign_existing_user
        if @task.position.assigned_user_id.nil?
            @task.position.assigned_user_id = @task.assigned_user.id
        elsif @task.assigned_user_id.nil?
            @task.assigned_user_id = @task.position.assigned_user.id
        else
        end
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :current_user, :company

    def index
    end

    def show
        @task = Task.find_by(id: params[:id])
        @segment = @task.segment
    end

    def edit
        @task = Task.find_by(id: params[:id])
    end

    def update
        @task = Task.find_by(id: params[:id])
        if @task.update(task_params)
            redirect_to segment_task_path(@task)
        else
            render :show
        end
    end

    private

    def task_params
        params.require(:task).permit(:title, :deadline, :description, :segment_id, :position_id, :completed,
        user_attributes: [
            :first_name,
            :last_name,
            :email,
            :password,
            :password_confirmation,
            :privilege,
            :user_param_value
        ],
        position_attributes: [
            :title,
            :description,
            :user_id
        ]).with_defaults(user_id: current_user.id)
    end
end

app/controllers/team_leader/project_comments_controller.rb
class TeamLeader::ProjectCommentsController < ApplicationController
    before_action :current_user, :company, :team_leader?
    layout "team_leader_layout"

    def index
    end

    def show
    end

    def new
    end

    def create
        @project = Project.find_by(id: params[:project_comment][:project_id])
        @project_comment = @project.project_comments.build(project_comment_params)
        if @project_comment.save
            redirect_to team_leader_project_path(@project)
        else
            render 'team_leader/project/show'
        end
    end

    def edit
    end
    
    def update
    end

    def destroy
        @project = ProjectComment.find_by(id: params[:id]).project
        ProjectComment.find_by(id: params[:id]).delete
        redirect_to team_leader_project_path(@project)
    end

    private

    def project_comment_params
        params.require(:project_comment).permit(:content).with_defaults(user_id: current_user.id, project_id: @project.id)
    end
end

app/controllers/team_leader/projects_controller.rb
class TeamLeader::ProjectsController < ApplicationController
    before_action :current_user, :company, :team_leader?
    layout "team_leader_layout"
    
    def index
        @project_index_links = params[:project_index_link]
        @projects = company.projects.ordered
    end

    def show
        @project = Project.find_by(id: params[:id])

        if params[:show_segment_form] == "true"
            @segment = Segment.new
        elsif params[:show_segment_and_team_form] == "true"
            @segment = Segment.new
            @team = @segment.build_team
        else
        end
    end
end

app/controllers/team_leader/segment_comments_controller.rb
class TeamLeader::SegmentCommentsController < ApplicationController
    before_action :current_user, :company, :team_leader?
    layout "team_leader_layout"

    def index
    end

    def show
    end

    def new
    end

    def create
        @segment = Segment.find_by(id: params[:segment_comment][:segment_id])
        @segment_comment = @segment.segment_comments.build(segment_comment_params)
        if @segment_comment.save
            redirect_to team_leader_segment_path(@segment)
        else
            render 'team_leader/segments/show'
        end
    end

    def edit
    end

    def update
    end

    def destroy
        @segment = SegmentComment.find_by(id: params[:id]).segment
        SegmentComment.find_by(id: params[:id]).delete
        redirect_to team_leader_segment_path(@segment)
    end

    private

    def segment_comment_params
        params.require(:segment_comment).permit(:content).with_defaults(user_id: current_user.id, segment_id: @segment.id)
    end
end

app/controllers/team_leader/segments_controller.rb
class TeamLeader::SegmentsController < ApplicationController
    before_action :current_user, :company, :team_leader?
    layout "team_leader_layout"

    def index
    end

    def show
        @segment = Segment.find_by(id: params[:id])
        if params[:show_task_form]=="true"
            @task = @segment.tasks.build
        elsif params[:show_task_and_user_form] == "true"
            @task = @segment.tasks.build
            @user = @task.build_user
            @positon = @task.build_position
            @show_task_and_user_form = true
        else
        end
    end
end

app/controllers/team_leader/task_comments_controller.rb
class TeamLeader::TaskCommentsController < ApplicationController
    before_action :current_user, :company, :team_leader?
    layout "team_leader_layout"

    def index
    end

    def show
    end

    def new
    end

    def create
        @task = Task.find_by(id: params[:task_comment][:task_id])
        @task_comment = @task.task_comments.build(task_comment_params)
        if @task_comment.save
            redirect_to team_leader_segment_task_path(@task.segment, @task)
        else
            render 'team_leader/tasks/show'
        end
    end

    def edit
    end

    def update
    end

    def destroy
        @task = TaskComment.find_by(id: params[:id]).task
        TaskComment.find_by(id: params[:id]).delete
        redirect_to team_leader_segment_task_path(@task.segment, @task)
    end

    private

    def task_comment_params
        params.require(:task_comment).permit(:content).with_defaults(user_id: current_user.id, task_id: @task.id)
    end
end

app/controllers/team_leader/tasks_controller.rb
class TeamLeader::TasksController < ApplicationController
    before_action :current_user, :company, :team_leader?
    layout "team_leader_layout"
    
    def index
    end
    
    def new
        @task = @segment.tasks.build
    end

    def create
        @segment = Segment.find_by(id: params[:task][:segment_id])
        @task = @segment.tasks.build(task_params)
        assign_existing_user
        if @task.save
            redirect_to admin_segment_path(@segment)
        else
            render 'admin/segments/show'
        end
    end

    def show
        @task = Task.find_by(id: params[:id])
        @segment = @task.segment
    end

    def edit
        @task = Task.find_by(id: params[:id])
        @segment = @task.segment
        @task.assigned_user.nil? ? @user=(User.new) : @user=(@task.assigned_user)
        @user.assigned_position.nil? ? @position=(Position.new) : @position=(@user.assigned_position)
        if params[:show_user_form]
            @show_user_form = params[:show_user_form]
        end
    end

    def update
        @task = Task.find_by(id: params[:id])
        if @task.update(task_params)
            redirect_to team_leader_segment_task_path(@task)
        else
            render :edit
        end
    end

    def destroy
        @task = Task.find_by(id: params[:id])
        @segment = @task.segment
        @task.destroy
        redirect_to admin_segment_path(@segment)
    end

    private

    def task_params
        params.require(:task).permit(:title, :deadline, :description, :segment_id, :position_id, :completed,
        user_attributes: [
            :first_name,
            :last_name,
            :email,
            :password,
            :password_confirmation,
            :privilege,
            :user_param_value
        ],
        position_attributes: [
            :title,
            :description,
            :user_id
        ]).with_defaults(user_id: current_user.id)
    end

    def assign_existing_user
        if @task.position.assigned_user_id.nil?
            @task.position.assigned_user_id = @task.assigned_user.id
        elsif @task.assigned_user_id.nil?
            @task.assigned_user_id = @task.position.assigned_user.id
        else
        end
    end
end

app/controllers/team_leader/teams_controller.rb
class TeamLeader::TeamsController < ApplicationController
    before_action :current_user, :company, :team_leader?
    layout "team_leader_layout"

    def index
        @team_index_link = params[:team_index_link]
    end

    def show
        @team = Team.find_by(id: params[:id])
        @current_user = current_user
        if params[:show_user_form] == "true"
            @position = @team.positions.build
            @user = @position.build_user
        end
    end

    private

    def team_params
        params.require(:team).permit(:name, :description).with_defaults(user_id: current_user.id, company_id: current_user.company.id)
    end
end

app/controllers/team_leader/users_controller.rb
class TeamLeader::UsersController < ApplicationController
    before_action :current_user, only: [:index, :show, :edit, :update, :delete,]
    before_action :team_leader?, only: [:index, :show, :edit, :update, :delete,]
    before_action :company
    layout "team_leader_layout"
    
    def index
    end

    def show
        @user = User.find_by(id: params[:id])
        @team = @user.team
    end

    def profile
        @user=(User.find_by(id: params[:id])) if params[:id]
        @current_user = current_user
        if !params[:show_form].nil? && params[:edit] == "edit"
            @edit_my_profile = true
            @position = @user.positions.build
            @team = @position.build_team
            @show_form = params[:show_form]
        elsif params[:edit] == "edit"
            @edit_my_profile = true
            @position = @user.positions.build
            @team = @position.build_team
        else
            @edit_my_profile = false
        end
    end

    def profile_form_handler
        @user = User.find_by(id: params[:id])
        @user.update(user_params)
        redirect_to "/team_leader/profile/#{@user.id}"
    end

    def new
        @user = User.new
        render layout: false
    end

    def create
        #create a new user as an team_leader
        else
            @user = User.new(user_params)
            @team = Team.find_by(id: params[:user][:position_attributes][:team_id])
            @position = @user.assigned_position
            if @user.save
                redirect_to team_leader_team_path(@team)
            else
                render "/team_leader/teams/show"
            end
        end
    end

    def edit
        @team = Team.find_by(id: params[:team_id])
        @user = User.find_by(id: params[:id])
        @position = @user.assigned_position
    end

    def update
        @team = Team.find_by(id: params[:user][:position_attributes][:team_id])
        @user = User.find_by(id: params[:id])
        
        if @user.update(user_params)
            @team = @user.team
            redirect_to team_leader_team_user_path(@team, @user)
        else
            @position = @user.assigned_position
            if @user.id == current_user.id
                @edit_my_profile = "true"
                render :profile
            else
            render "/team_leader/teams/1?show_user_form=true"
            end
        end
    end

    def destroy
        @user = User.find_by(id: params[:id])
        @team = @user.team
        @user.position.delete && @user.delete
        redirect_to team_leader_team_path(@team)
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :privilege,
            :team_attributes => [
                :name,
                :description,
                :id,
                :profile #for determining if the form came from the profile page. Do not allow into update or create method for team
            ],
            position_attributes: [
                :title,
                :description,
                :team_id,
            ],
        ).with_defaults(user_id: current_user.id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/team_leader/tasks/_completed_form.html.erb
<%= form_for [:team_leader, @task.segment, @task] do |f| %>
  <% if @task.completed == false %>
    Mark if task is completed: 
    <%= f.radio_button :completed, true, { onchange: 'this.form.submit();' } %>
  <% else %>
    Mark if task is incomplete:
    <%= f.radio_button :completed, false, { onchange: 'this.form.submit();' } %>
  <% end %>
<% end %>

app/views/team_leader/tasks/_form.html.erb
<% if @task.errors.any? %>
    <h3>Errors:</h3>
        <ul class="error-content">
    <% @task.errors.full_messages.each do |message| %>
            <li><%= message %>
          <% end %>
        </ul>
<% end %>

<%= form_for [:admin, @segment, @task] do |task_builder| %>
    <%= task_builder.hidden_field :segment_id, :value => @segment.id %>
    Title: <%= task_builder.text_field :title, required: true, placeholder: "Enter the new Tasks's title..." %>
    Deadline: <%= task_builder.date_field :deadline, required: true %>
    Description: <%= task_builder.text_area :description, required: true, placeholder: "Enter the new Task's description..." %><br><br>

      <% if @show_task_and_user_form.nil? && @segment.team.positions != [] %>
        <p>Pick a Team Member:<p> <%= task_builder.collection_select :position_id, @segment.team.positions, :id, :title, {:include_blank => true} %>
        or <%= link_to "Add User", admin_project_segment_path(@segment.project, @segment, :show_task_and_user_form => true) if @task && @user.nil? %>
      <% end %>

        <% if @segment.team.positions == [] %>
        <p>You currently have not created any team members in this team. You need to create a team member before you can create a task.</p>
        <% end %>

        <% if @task.assigned_user %>
          <br><br><%= link_to "Edit Task's Assigned Team Member", edit_team_leader_segment_task_path(@task.segment, @task, :show_user_form => "edit_user") unless @show_user_form || @task.id.nil? %>
        <% else %>
          <br><br><%= link_to "Create Task's Assigned Team Member", edit_team_leader_segment_task_path(@task.segment, @task, :show_user_form => "create_user") unless @show_user_form || @task.id.nil?%>
        <% end %>

        <% if @show_user_form || @task.assigned_user.nil? %>

          <%= task_builder.fields_for :user, @user do |user_builder| %>
          <br><h3><%= @user.nil? || @user.id.nil? ? "New Team Member" : "Edit Team Member" %></h3><br>
          <%= user_builder.hidden_field :user_param_value, :value => "#{@show_user_form}" %>
          First Name: <%= user_builder.text_field :first_name, required: true %><br><br>
          Last Name: <%= user_builder.text_field :last_name, required: true %><br><br>
          Email: <%= user_builder.text_field :email, required: true %><br><br>
          Password: <%= user_builder.password_field :password, :placeholder => "Not required for edit..." %><br><br>
          Re-Password: <%= user_builder.password_field :password_confirmation, :placeholder => "Not required for edit..." %><br><br>
          Privlages: <br><br>
          Admin: <%= user_builder.radio_button :privilege, "Admin", required: true%><br>
          Team Leader: <%= user_builder.radio_button :privilege, "Team Leader", required: true%><br>
          Team Member: <%= user_builder.radio_button :privilege, "Team Member", required: true%><br><br>

          <%= task_builder.fields_for :position, @position do |position_builder| %>
          Position Title: <%= position_builder.text_field :title %>
          Position Description: <%= position_builder.text_area :description %>
            <% end %><br>
        <% end %>
      <br><%= task_builder.submit "Submit Task" %>
  <% end %>
<% end %>

app/views/team_leader/tasks/_show_comments.html.erb
<br><br>Comments: <br><br>

<% @task.task_comments.each do |comment| %>
  <% if @task.task_comments.all == [] %>
    <p>There are no comments to view on this post.</p>
  <% else %>
      <% if !comment.id.nil? || !comment.content.nil?%>
        <%= comment.user.full_name %><br>
        <%= comment.content %>
        <%= link_to "delete", [:team_leader, comment], confirm: "Are you sure?", :method => "delete" %>
    <% end %><br><br>
  <% end %>
<% end %>

app/views/team_leader/tasks/show.html.erb
<div id="container-fluid">
  <div class="row">
    <div class="col-lg" style="border:1px solid #ccc;overflow:auto;">
      <div class="<%=display_progress(@task)%>-col-content">

        <h1><%= @task.title %></h1>
        <%= link_to "Update Task", edit_team_leader_segment_task_path(@task.segment, @task) if @current_user.team == @task.segment.team %>
        <%= link_to "Delete Task", [:team_leader, @task.segment, @task], confirm: "Are you sure?", :method => :delete if @current_user.team == @task.segment.team %><br><br>
        <%= render :partial => "team_leader/tasks/completed_form" %><br>
        <%= @task.description %><br><br>
        Assigned Team Member: <%= link_to "#{@task.assigned_user.full_name}", team_leader_team_user_path(@task.assigned_user.team, @task.assigned_user) %><br><br>

      </div>
    </div>
  </div>
</div>

<%= render :partial => 'team_leader/task_comments/form', :locals => { :subject => @task } %>

<%= render :partial => "team_leader/tasks/show_comments" %><br>