config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/auth/github/callback', to: 'sessions#create'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'
  get '/signup', to: 'users#new'
  post '/signup', to: "users#create"

  root to: "application#home"

  # admin ----------------------------------------

  get '/admin/home', to: "application#admin_home"

  scope module: 'admin' do
  get '/admin/profile/:id', to: 'users#profile'
  patch '/admin/profile/:id', to: 'users#profile_form_handler'
  get '/admin/profile/:id/:edit', to: 'users#profile'
  get '/admin/profile/:id/:edit/:show_form', to: 'users#profile'
  end

  namespace :admin do
    resources :projects

    resources :projects, only: [:show] do
      resources :segments, only: [:show, :new, :create, :edit, :update, :destroy]
    end

    resources :segments, only: [:show] do
      resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy]
    end

    resources :teams

    resources :teams, only: [:show] do
      resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
    end

    resources :project_comments
    resources :segment_comments
    resources :task_comments
end

# Team Member ----------------------------------------

resources :projects, only: [:index, :show]

    resources :projects, only: [:show] do
      resources :segments, only: [:show]
    end

    resources :segments, only: [:show] do
      resources :tasks, only: [:show, :edit, :update]
    end

    resources :teams, only: [:index]

    resources :teams, only: [:show] do
      resources :users, only: [:show]
    end

    resources :tasks, only: [:index, :edit, :update]

    resources :project_comments
    resources :segment_comments
    resources :task_comments

  get '/profile/:id', to: 'users#profile'
  patch '/profile/:id', to: 'users#profile_form_handler'
  get '/profile/:id/:edit', to: 'users#profile'
  get '/profile/:id/:edit/:show_form', to: 'users#profile'

  # Team Leader ----------------------------------------

  get '/team-leader/home', to: "application#team_leader_home"
  
  scope module: 'team_leader' do
    get '/team_leader/profile/:id', to: 'users#profile'
    patch '/team_leader/profile/:id', to: 'users#profile_form_handler'
    get '/team_leader/profile/:id/:edit', to: 'users#profile'
    get '/team_leader/profile/:id/:edit/:show_form', to: 'users#profile'
    end
  
    namespace :team_leader do
      resources :projects, only: [:index, :show] do
        resources :segments, only: [:show, :edit, :update]
      end
  
      resources :segments, only: [:show] do
        resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy]
      end
      resources :teams, only: [:index]
    
      resources :teams, only: [:show] do
        resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
      end
  
      resources :project_comments
      resources :segment_comments
      resources :task_comments
  end

  # match must be last route

  match '*path', to: "application#notfound", via: [:get, :post]

  # Which routes need to be namespaced??

  # Admin Routes:

  #  All routes should be accessable to admin



  # Team Leader Routes:

  # Team leaders can only create tasks, create users, mark tasks and segments completed


  # Team Member Routes:

  # Team members can only edit their profile, mark tasks as completed, and comment.

  # routes that edit 
end

app/models/project.rb
class Project < ApplicationRecord
    belongs_to :company
    belongs_to :user
    has_many :segments, dependent: :destroy
    has_many :teams, through: :segments
    has_many :project_comments, dependent: :destroy
    has_many :users, through: :project_comments

    validates :title, :description, presence: { message: "Project Fields must be filled and longer than 2 characters"}, length: { minimum: 2}
    validates :deadline, presence: { message: "You must assign a deadline to your Project"}

    scope :completed, -> { where(completed: true)}
    scope :incomplete, -> { where(completed: false)}
    scope :ordered, -> { order "deadline ASC" }
    scope :late, lambda { where('deadline < ?', Date.today).where(completed: false) }
    scope :search_title, -> (title) { where("title LIKE ?", "%#{title}%") }

    def ordered_segments
        self.segments.ordered
    end

    def completed_segments
        self.segments.ordered.completed
    end

    def incomplete_segments
        self.segments.ordered.incomplete
    end

    def late
        self.deadline < Date.today
    end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < ApplicationController
    before_action :current_user, :company, :admin?
    layout "admin_layout"
    
    def index
        @project_index_links = params[:project_index_link]
        @projects = company.projects.ordered

        if params[:project] 
            @projects = @company.projects.search_title(params[:project])
        end
    end

    def show
        @project = Project.find_by(id: params[:id])
        if params[:show_segment_form] == "true"
            @segment = Segment.new
        elsif params[:show_segment_and_team_form] == "true"
            @segment = Segment.new
            @team = @segment.build_team
            @show_segment_and_team_form = params[:show_segment_and_team_form]
        else
        end
    end

    def new
        @project = current_user.projects.build
    end

    def create
        @project = current_user.projects.build(project_params)
        @project.company = current_user.company

        if @project.save
            redirect_to admin_project_path(@project)
        else
            render :new
        end
    end

    def edit
        @project = Project.find_by(id: params[:id])
    end

    def update
        @project = Project.find_by(id: params[:id])
        if @project.update(project_params)
        redirect_to admin_project_path(@project)
        else
        render :edit
        end
    end

    def destroy
        Project.find_by(id: params[:id]).destroy
        redirect_to admin_projects_path
    end

    private

    def project_params
    params.require(:project).permit(:title, :deadline, :description, :completed, company: current_user.company,
        :segment_attributes => [
            :title,
            :deadline,
            :description
        ]
    )
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :current_user, :company
    
    def index
        @project_index_links = params[:project_index_link]
        @projects = company.projects.ordered
    end

    def show
        @project = Project.find_by(id: params[:id])

        if params[:show_segment_form] == "true"
            @segment = Segment.new
        elsif params[:show_segment_and_team_form] == "true"
            @segment = Segment.new
            @team = @segment.build_team
        else
        end
    end
end

app/controllers/team_leader/projects_controller.rb
class TeamLeader::ProjectsController < ApplicationController
    before_action :current_user, :company, :team_leader?
    layout "team_leader_layout"
    
    def index
        @project_index_links = params[:project_index_link]
        @projects = company.projects.ordered
    end

    def show
        @project = Project.find_by(id: params[:id])

        if params[:show_segment_form] == "true"
            @segment = Segment.new
        elsif params[:show_segment_and_team_form] == "true"
            @segment = Segment.new
            @team = @segment.build_team
        else
        end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
    def pretty_deadline(arg)
        arg.deadline.strftime("Deadline: %m/%d/%Y")
    end

    def completed(arg)
        if arg.completed
            "This #{arg.class} has been completed."
        else
            "This #{arg.class} is incomplete."
        end
    end
end

app/views/projects/_index_form.html.erb
<% @projects.ordered.each do |project| %>
  <div class="<%=display_progress(project)%>-col-content"><br><br>
    <h2><%= link_to "#{project.title}", project_path(project)%><br></h2>
    <strong><%= pretty_deadline(project) %></strong><br>
    <%= project.description %><br><br>
    <h3><strong>Segments</strong>:</h3>
      <% if project.segments.empty?%>
        There are no segments associated with this project
      <% else %>
       <% project.segments.ordered.each do |segment| %>
        <div class="<%=display_progress(segment)%>-inner-content">
          <h4><%= link_to "#{segment.title}", project_segment_path(project, segment) %><br></h4>
          <strong><%= pretty_deadline(segment) %></strong><br>
          <%= segment.description %><br>
          <%= completed(segment)%>
        </div>
      <% end %>
    </div>
  <% end %><br><br>
<% end %>

app/views/projects/_show_comments.html.erb
Comments: <br><br>
  
<% @project.project_comments.each do |comment| %>
  <% comment.delete if comment.id.nil?%>
  <% if @project.project_comments.all == [] %>
    <p>There are no comments to view on this post.</p>
  <% else %>
      <% if !comment.id.nil? || !comment.content.nil?%>
        <%= link_to "#{comment.user.full_name}", team_user_path(comment.user) %><br>
        <%= comment.content %><br>
        <%= link_to "delete", comment, :method => :delete %>
    <% end %>
  <% end %>
<% end %>

app/views/projects/_show_complete_projects.html.erb
<% if @company.projects.completed.empty? %>
        <p>There are no complete Projects!</p>
<% else %>
  <% @company.projects.completed.each do |project| %>
    <div class="<%=display_progress(project)%>-col-content">
      <h2><%= link_to "#{project.title}", project_path(project)%><br></h2>
      <strong><%= pretty_deadline(project) %></strong><br><br>
      <%= project.description %><br><br>

      <h3><strong>Segments</strong>:</h3>
      <% if project.segments.empty?%>
          <p>You do not have any segments associated with this project</p>
      <% else %>
        <% project.segments.ordered.each do |segment| %>
          <div class="<%=display_progress(segment)%>-inner-content">
              <h4><%= link_to "#{segment.title}", project_segment_path(project, segment) %><br></h4>
              <strong><%= pretty_deadline(segment) %></strong><br>
              <%= segment.description %><br>
              <%= completed(segment)%>
          </div>
      <% end %>
    </div>
    <% end %><br><br>
  <% end %>
<% end %>

app/views/projects/_show_incomplete_projects.html.erb
<% if @company.projects.incomplete.empty? %>
    <p>There are no incomplete Projects!</p>
  <% else %>
  <% @company.projects.incomplete.each do |project| %>
    <div class="<%=display_progress(project)%>-col-content">
      <h2><%= link_to "#{project.title}", project_path(project)%><br></h2>
      <strong><%= pretty_deadline(project) %></strong><br>
      <%= project.description %><br><br>
      <h3><strong>Segments</strong>:</h3>

    <% if project.segments.empty?%>
      <p>You do not have any segments associated with this project</p>
    <% else %>
      <% project.segments.ordered.each do |segment| %>
        <div class="<%=display_progress(segment)%>-inner-content">
          <h4><%= link_to "#{segment.title}", project_segment_path(project, segment) %><br></h4>
          <strong><%= pretty_deadline(segment) %></strong><br>
          <%= segment.description %><br>
          <%= completed(segment)%>
        </div>
      <% end %>
    <% end %><br><br>
  <% end %>
<% end %>

app/views/projects/_show_segments.html.erb
<% if @project.nil? %>
<% elsif @project.segments == [] %>
    <p>You have no segments for this project.</p>
<% else %>
    <% @project.segments.ordered.each do |segment| %>
        <div class="<%=display_progress(segment)%>-inner-content">
        <%= link_to("#{segment.title}", project_segment_path(@project.id, segment.id)) %><br>
        Team: <%= link_to "#{segment.team.name}", team_path(segment.team) %><br>
        <%= "#{segment.description}" %><br><br>
        </div>
    <% end %>
<% end %>

app/views/projects/index.html.erb
<div id="container-fluid">
  <div class="row">
    <div class="col-lg" style="border:1px solid #ccc;overflow:auto;">

      <ul style="text-align: center;padding:20px;">
        <strong><li style="font-size: 20px;"><%= link_to "#{@company.name}'s Projects", projects_path %></li></strong> | 
        <li><%= link_to "Completed Projects", projects_path(:project_index_link => "complete") %></li> | 
        <li><%= link_to "Incomplete Projects", projects_path(:project_index_link => "incomplete") %></li> | 
      </ul><br><br>
  
      <% if @project_index_links == "complete" %>
          <%= render :partial => "projects/show_complete_projects" %>
      <% elsif @project_index_links == "incomplete" %>
          <%= render :partial => "projects/show_incomplete_projects" %>
      <% else %>
          <%= render :partial => "projects/index_form" %>
      <% end %>

    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div id="container-fluid">
  <div class="row">
    <div class="col-lg" style="border:1px solid #ccc;overflow:auto;">
      <div class="<%=display_progress(@project)%>-col-content">

        <h1><%= @project.title %></h1>
        <%= pretty_deadline(@project) %><br>
        <%= @project.description %><br><br>

        <%= render :partial => "projects/completed_form" %><br>

        <h3>Segments:</h3>
        <%= render :partial => "projects/show_segments" %>

        <%= render :partial => 'segments/form', :locals => { :segment => @segment } if @segment %><br>

      </div>
    </div>
  </div>
</div>

<%= render :partial => 'project_comments/form', :locals => { :subject => @project } %>

<br><%= render :partial => "projects/show_comments" %>