config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/auth/github/callback', to: 'sessions#create'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'
  get '/signup', to: 'users#new'
  post '/signup', to: "users#create"

  root to: "application#home"

  # admin ----------------------------------------

  get '/admin/home', to: "application#admin_home"

  scope module: 'admin' do
  get '/admin/profile/:id', to: 'users#profile'
  patch '/admin/profile/:id', to: 'users#profile_form_handler'
  get '/admin/profile/:id/:edit', to: 'users#profile'
  get '/admin/profile/:id/:edit/:show_form', to: 'users#profile'
  end

  namespace :admin do
    resources :projects

    resources :projects, only: [:show] do
      resources :segments, only: [:show, :new, :create, :edit, :update, :destroy]
    end

    resources :segments, only: [:show] do
      resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy]
    end

    resources :teams

    resources :teams, only: [:show] do
      resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
    end

    resources :project_comments
    resources :segment_comments
    resources :task_comments
end

# Team Member ----------------------------------------

resources :projects, only: [:index, :show]

    resources :projects, only: [:show] do
      resources :segments, only: [:show]
    end

    resources :segments, only: [:show] do
      resources :tasks, only: [:show, :edit, :update]
    end

    resources :teams, only: [:index]

    resources :teams, only: [:show] do
      resources :users, only: [:show]
    end

    resources :tasks, only: [:index, :edit, :update]

    resources :project_comments
    resources :segment_comments
    resources :task_comments

  get '/profile/:id', to: 'users#profile'
  patch '/profile/:id', to: 'users#profile_form_handler'
  get '/profile/:id/:edit', to: 'users#profile'
  get '/profile/:id/:edit/:show_form', to: 'users#profile'

  # Team Leader ----------------------------------------

  get '/team-leader/home', to: "application#team_leader_home"
  
  scope module: 'team_leader' do
    get '/team_leader/profile/:id', to: 'users#profile'
    patch '/team_leader/profile/:id', to: 'users#profile_form_handler'
    get '/team_leader/profile/:id/:edit', to: 'users#profile'
    get '/team_leader/profile/:id/:edit/:show_form', to: 'users#profile'
    end
  
    namespace :team_leader do
      resources :projects, only: [:index, :show] do
        resources :segments, only: [:show, :edit, :update]
      end
  
      resources :segments, only: [:show] do
        resources :tasks, only: [:show, :new, :create, :edit, :update, :destroy]
      end
      resources :teams, only: [:index]
    
      resources :teams, only: [:show] do
        resources :users, only: [:show, :new, :create, :edit, :update, :destroy]
      end
  
      resources :project_comments
      resources :segment_comments
      resources :task_comments
  end

  # match must be last route

  match '*path', to: "application#notfound", via: [:get, :post]

  # Which routes need to be namespaced??

  # Admin Routes:

  #  All routes should be accessable to admin



  # Team Leader Routes:

  # Team leaders can only create tasks, create users, mark tasks and segments completed


  # Team Member Routes:

  # Team members can only edit their profile, mark tasks as completed, and comment.

  # routes that edit 
end

app/controllers/admin/teams_controller.rb
class Admin::TeamsController < ApplicationController
    before_action :current_user, :company, :admin?
    layout "admin_layout"

    def index
        @team_index_link = params[:team_index_link]
    end

    def show
        @team = Team.find_by(id: params[:id])
        if params[:show_user_form] == "true"
            @position = @team.positions.build
            @user = @position.build_user
        end
    end

    def new
        @team = Team.new
    end

    def create
        @team = Team.new(team_params)
        if @team.save
            redirect_to admin_team_path(@team)
        else
            render :new
        end
    end

    def edit
        @team = Team.find_by(id: params[:id])
    end

    def update
        @team = Team.find_by(id: params[:id])
        if @team.update(team_params)
            redirect_to admin_team_path(@team)
        else
            render :edit
        end
    end

    def destroy
        @team = Team.find_by(id: params[:id])

        if @team.positions.empty? && @team.segments.empty?
            @team.delete
            redirect_to admin_teams_path
        else
            flash[:message] = "A Team cannot be deleted while it has members or segments! Relocate or delete all members and segments in order to delete #{@team.name}."
            render :show
        end
    end

    private

    def team_params
        params.require(:team).permit(:name, :description).with_defaults(user_id: current_user.id, company_id: current_user.company.id)
    end
end

app/controllers/team_controller.rb
class TeamsController < ApplicationController
    before_action :current_user, :company

    def index
    end

    def show
        @team = Team.find_by(id: params[:id])
        if params[:show_user_form] == "true"
            @position = @team.positions.build
            @user = @position.build_user
        end
    end

    def new
        @team = Team.new
    end

    def create
        @team = Team.new(team_params)
        if @team.save
            redirect_to @team
        else
            render :new
        end
    end

    def edit
        @team = Team.find_by(id: params[:id])
    end

    def update
        @team = Team.find_by(id: params[:id])
        if @team.update(team_params)
            redirect_to @team
        else
            render :edit
        end
    end

    def destroy
        Team.find_by(id: params[:id]).positions.each do |position|
            position.assigned_user.delete
            position.delete
        end
        Team.find_by(id: params[:id]).delete
        redirect_to "/"
    end

    private

    def team_params
        params.require(:team).permit(:name, :description).with_defaults(user_id: current_user.id, company_id: current_user.company.id)
    end
end

app/controllers/team_leader/project_comments_controller.rb
class TeamLeader::ProjectCommentsController < ApplicationController
    before_action :current_user, :company, :team_leader?
    layout "team_leader_layout"

    def index
    end

    def show
    end

    def new
    end

    def create
        @project = Project.find_by(id: params[:project_comment][:project_id])
        @project_comment = @project.project_comments.build(project_comment_params)
        if @project_comment.save
            redirect_to team_leader_project_path(@project)
        else
            render 'team_leader/project/show'
        end
    end

    def edit
    end
    
    def update
    end

    def destroy
        @project = ProjectComment.find_by(id: params[:id]).project
        ProjectComment.find_by(id: params[:id]).delete
        redirect_to team_leader_project_path(@project)
    end

    private

    def project_comment_params
        params.require(:project_comment).permit(:content).with_defaults(user_id: current_user.id, project_id: @project.id)
    end
end

app/controllers/team_leader/projects_controller.rb
class TeamLeader::ProjectsController < ApplicationController
    before_action :current_user, :company, :team_leader?
    layout "team_leader_layout"
    
    def index
        @project_index_links = params[:project_index_link]
        @projects = company.projects.ordered
    end

    def show
        @project = Project.find_by(id: params[:id])

        if params[:show_segment_form] == "true"
            @segment = Segment.new
        elsif params[:show_segment_and_team_form] == "true"
            @segment = Segment.new
            @team = @segment.build_team
        else
        end
    end
end

app/controllers/team_leader/segment_comments_controller.rb
class TeamLeader::SegmentCommentsController < ApplicationController
    before_action :current_user, :company, :team_leader?
    layout "team_leader_layout"

    def index
    end

    def show
    end

    def new
    end

    def create
        @segment = Segment.find_by(id: params[:segment_comment][:segment_id])
        @segment_comment = @segment.segment_comments.build(segment_comment_params)
        if @segment_comment.save
            redirect_to team_leader_segment_path(@segment)
        else
            render 'team_leader/segments/show'
        end
    end

    def edit
    end

    def update
    end

    def destroy
        @segment = SegmentComment.find_by(id: params[:id]).segment
        SegmentComment.find_by(id: params[:id]).delete
        redirect_to team_leader_segment_path(@segment)
    end

    private

    def segment_comment_params
        params.require(:segment_comment).permit(:content).with_defaults(user_id: current_user.id, segment_id: @segment.id)
    end
end

app/controllers/team_leader/segments_controller.rb
class TeamLeader::SegmentsController < ApplicationController
    before_action :current_user, :company, :team_leader?
    layout "team_leader_layout"

    def index
    end

    def show
        @segment = Segment.find_by(id: params[:id])
        if params[:show_task_form]=="true"
            @task = @segment.tasks.build
        elsif params[:show_task_and_user_form] == "true"
            @task = @segment.tasks.build
            @user = @task.build_user
            @positon = @task.build_position
            @show_task_and_user_form = true
        else
        end
    end
end

app/controllers/team_leader/task_comments_controller.rb
class TeamLeader::TaskCommentsController < ApplicationController
    before_action :current_user, :company, :team_leader?
    layout "team_leader_layout"

    def index
    end

    def show
    end

    def new
    end

    def create
        @task = Task.find_by(id: params[:task_comment][:task_id])
        @task_comment = @task.task_comments.build(task_comment_params)
        if @task_comment.save
            redirect_to team_leader_segment_task_path(@task.segment, @task)
        else
            render 'team_leader/tasks/show'
        end
    end

    def edit
    end

    def update
    end

    def destroy
        @task = TaskComment.find_by(id: params[:id]).task
        TaskComment.find_by(id: params[:id]).delete
        redirect_to team_leader_segment_task_path(@task.segment, @task)
    end

    private

    def task_comment_params
        params.require(:task_comment).permit(:content).with_defaults(user_id: current_user.id, task_id: @task.id)
    end
end

app/controllers/team_leader/tasks_controller.rb
class TeamLeader::TasksController < ApplicationController
    before_action :current_user, :company, :team_leader?
    layout "team_leader_layout"
    
    def index
    end
    
    def new
        @task = @segment.tasks.build
    end

    def create
        @segment = Segment.find_by(id: params[:task][:segment_id])
        @task = @segment.tasks.build(task_params)
        assign_existing_user
        if @task.save
            redirect_to admin_segment_path(@segment)
        else
            render 'admin/segments/show'
        end
    end

    def show
        @task = Task.find_by(id: params[:id])
        @segment = @task.segment
    end

    def edit
        @task = Task.find_by(id: params[:id])
        @segment = @task.segment
        @task.assigned_user.nil? ? @user=(User.new) : @user=(@task.assigned_user)
        @user.assigned_position.nil? ? @position=(Position.new) : @position=(@user.assigned_position)
        if params[:show_user_form]
            @show_user_form = params[:show_user_form]
        end
    end

    def update
        @task = Task.find_by(id: params[:id])
        if @task.update(task_params)
            redirect_to team_leader_segment_task_path(@task)
        else
            render :edit
        end
    end

    def destroy
        @task = Task.find_by(id: params[:id])
        @segment = @task.segment
        @task.destroy
        redirect_to admin_segment_path(@segment)
    end

    private

    def task_params
        params.require(:task).permit(:title, :deadline, :description, :segment_id, :position_id, :completed,
        user_attributes: [
            :first_name,
            :last_name,
            :email,
            :password,
            :password_confirmation,
            :privilege,
            :user_param_value
        ],
        position_attributes: [
            :title,
            :description,
            :user_id
        ]).with_defaults(user_id: current_user.id)
    end

    def assign_existing_user
        if @task.position.assigned_user_id.nil?
            @task.position.assigned_user_id = @task.assigned_user.id
        elsif @task.assigned_user_id.nil?
            @task.assigned_user_id = @task.position.assigned_user.id
        else
        end
    end
end

app/controllers/team_leader/teams_controller.rb
class TeamLeader::TeamsController < ApplicationController
    before_action :current_user, :company, :team_leader?
    layout "team_leader_layout"

    def index
        @team_index_link = params[:team_index_link]
    end

    def show
        @team = Team.find_by(id: params[:id])
        @current_user = current_user
        if params[:show_user_form] == "true"
            @position = @team.positions.build
            @user = @position.build_user
        end
    end

    private

    def team_params
        params.require(:team).permit(:name, :description).with_defaults(user_id: current_user.id, company_id: current_user.company.id)
    end
end

app/controllers/team_leader/users_controller.rb
class TeamLeader::UsersController < ApplicationController
    before_action :current_user, only: [:index, :show, :edit, :update, :delete,]
    before_action :team_leader?, only: [:index, :show, :edit, :update, :delete,]
    before_action :company
    layout "team_leader_layout"
    
    def index
    end

    def show
        @user = User.find_by(id: params[:id])
        @team = @user.team
    end

    def profile
        @user=(User.find_by(id: params[:id])) if params[:id]
        @current_user = current_user
        if !params[:show_form].nil? && params[:edit] == "edit"
            @edit_my_profile = true
            @position = @user.positions.build
            @team = @position.build_team
            @show_form = params[:show_form]
        elsif params[:edit] == "edit"
            @edit_my_profile = true
            @position = @user.positions.build
            @team = @position.build_team
        else
            @edit_my_profile = false
        end
    end

    def profile_form_handler
        @user = User.find_by(id: params[:id])
        @user.update(user_params)
        redirect_to "/team_leader/profile/#{@user.id}"
    end

    def new
        @user = User.new
        render layout: false
    end

    def create
        #create a new user as an team_leader
        else
            @user = User.new(user_params)
            @team = Team.find_by(id: params[:user][:position_attributes][:team_id])
            @position = @user.assigned_position
            if @user.save
                redirect_to team_leader_team_path(@team)
            else
                render "/team_leader/teams/show"
            end
        end
    end

    def edit
        @team = Team.find_by(id: params[:team_id])
        @user = User.find_by(id: params[:id])
        @position = @user.assigned_position
    end

    def update
        @team = Team.find_by(id: params[:user][:position_attributes][:team_id])
        @user = User.find_by(id: params[:id])
        
        if @user.update(user_params)
            @team = @user.team
            redirect_to team_leader_team_user_path(@team, @user)
        else
            @position = @user.assigned_position
            if @user.id == current_user.id
                @edit_my_profile = "true"
                render :profile
            else
            render "/team_leader/teams/1?show_user_form=true"
            end
        end
    end

    def destroy
        @user = User.find_by(id: params[:id])
        @team = @user.team
        @user.position.delete && @user.delete
        redirect_to team_leader_team_path(@team)
    end

    private

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :privilege,
            :team_attributes => [
                :name,
                :description,
                :id,
                :profile #for determining if the form came from the profile page. Do not allow into update or create method for team
            ],
            position_attributes: [
                :title,
                :description,
                :team_id,
            ],
        ).with_defaults(user_id: current_user.id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
    before_action :current_user, :company

    def index
        @team_index_link = params[:team_index_link]
    end

    def show
        @team = Team.find_by(id: params[:id])
        if params[:show_user_form] == "true"
            @position = @team.positions.build
            @user = @position.build_user
        end
    end
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/team_leader/teams/_show_all_teams.html.erb
<% @company.teams.each do |team| %>
    <h3><%= link_to "#{team.name}", team_leader_team_path(team) %></h3>
    <%= team.description %><br>
    <% if team.leaders.empty? %>
      <div class="inner-content">
        <p>This team has no assigned leaders</p>
      </div>
    <% else %>
    <h2 style="margin-top:10px;" >Leaders</h2>
      <% team.leaders.each do |user| %>
        <div class="inner-content">
          <%= link_to "#{user.full_name}", team_leader_team_user_path(team, user) %>, <%= user.privilege %>:<br>
          <%= user.assigned_position.title %> - <%= user.assigned_position.description %><br>
          <%= user.email %><br><br>
        </div>
      <%end%>
    <%end%><br><br>    
<%end%><br>

app/views/team_leader/teams/_show_complete_projects.html.erb
<% @arr = []%>

<div id="container-fluid">
  <div class="row">
    <div class="col-lg" style="border:1px solid #ccc;overflow:auto;">
  
<% @company.teams.each do |team| %>

<% if team.segments.completed.empty?%>
<% else%>
      <% @team = team %>
      <h3 style="margin-bottom:2%">Team: <%= link_to "#{team.name}", team_leader_team_path(team) %><br>completed segments:</h3>
        <% team.segments.completed.ordered.each do |segment| %>
        <% @segment = segment %>
        <% @arr << segment %>

        <div class="<%=display_progress(segment)%>-inner-content">
        <h4><%= link_to "#{segment.title}", team_leader_project_segment_path(segment.project, segment)%></h4>
        <p style="font-size:20px;margin:0%"><%= pretty_deadline(segment) %></p>
        <p style="font-size:20px;margin:0;">Description: <%= segment.description %></p>
        <p style="font-size:20px;margin:0;">Project: <%= link_to "#{segment.project.title}", team_leader_project_path(segment.project)%>, <%= pretty_deadline(segment.project) %></p>
        <%= render :partial => "team_leader/segments/completed_form" if @current_user.team == team %>
          </div>
        <% end %>
      <% end %><br><br>
    <% end %><br><br>
    </div>
  </div>
</div>

<p style="text-align: center;"><%= "There are no completed segments!" if @arr.empty? %><p>

app/views/team_leader/teams/_show_incomplete_projects.html.erb
<% @arr = []%>
<div id="container-fluid">
  <div class="row">
    <div class="col-lg" style="border:1px solid #ccc;overflow:auto;">
  
<% @company.teams.each do |team| %>

<% if team.segments.incomplete.empty?%>
<% else%>
      <% @team = team %>
      <h3 style="margin-bottom:2%">Team: <%= link_to "#{team.name}", team_leader_team_path(team) %><br>incomplete segments:</h3>
        <% team.segments.incomplete.ordered.each do |segment| %>
        <% @segment = segment %>
        <% @arr << segment %>

        <div class="<%=display_progress(segment)%>-inner-content">
        <h4><%= link_to "#{segment.title}", team_leader_project_segment_path(segment.project, segment)%></h4>
        <p style="font-size:20px;margin:0%"><%= pretty_deadline(segment) %></p>
        <p style="font-size:20px;margin:0;">Description: <%= segment.description %></p>
        <p style="font-size:20px;margin:0;">Project: <%= link_to "#{segment.project.title}", team_leader_project_path(segment.project)%>, <%= pretty_deadline(segment.project) %></p>
        <%= render :partial => "team_leader/segments/completed_form" if @current_user.team == team %>
          </div>
        <% end %>
      <% end %><br><br>
    <% end %><br><br>
    </div>
  </div>
</div>

<p style="text-align: center;"><%= "There are no incomplete segments!" if @arr.empty? %><p>

app/views/team_leader/teams/_show_team.html.erb
<% if !@team.nil? && !@team.positions.empty? %>
    <% @team.positions.each do |position| %>
        <div class="inner-content" %>
            <p style="font-size: 20px;"><%= link_to "#{position.assigned_user.full_name}", team_leader_team_user_path(@team.id, position.assigned_user.id) %> 
            - <%= position.title %></p>
            <%= position.assigned_user.email %><br>
            <%= link_to "View #{position.assigned_user.first_name}'s active tasks", team_leader_team_user_path(@team.id, position.assigned_user.id) %><br><br>
        </div><br>
    <% end %>
<% else %>
    <p>You don't have any members in this team.</p>
<% end %>

app/views/team_leader/teams/index.html.erb
<div id="container-fluid">
  <div class="row">
    <div class="col-lg" style="border:1px solid #ccc;overflow:auto;">

      <ul style="text-align: center;padding:20px;">
        <strong><li style="font-size: 20px;"><%= link_to "#{@current_user.company.name}'s Teams", team_leader_teams_path %></li></strong> | 
        <li><%= link_to "Complete Segments", team_leader_teams_path(:team_index_link => "complete") %></li> | 
        <li><%= link_to "Incomplete Segments", team_leader_teams_path(:team_index_link => "incomplete") %></li> | 
      </ul>

      <% if @team_index_link == "complete" %>
          <%= render :partial => "team_leader/teams/show_complete_projects" %>
      <% elsif @team_index_link == "incomplete" %>
          <%= render :partial => "team_leader/teams/show_incomplete_projects" %>
      <% else %>
          <%= render :partial => "team_leader/teams/show_all_teams" %>
      <% end %>

    </div>
  </div>
</div>

app/views/team_leader/teams/show.html.erb
<div id="container-fluid">
  <div class="row">
    <div class="col-lg" style="border:1px solid #ccc;overflow:auto;">

      <ul style="text-align: center;padding:20px;">
          <strong><li style="font-size: 20px;"><%= link_to "#{@current_user.company.name}'s Teams", team_leader_teams_path %></li></strong> 
          <li><%= link_to "| Create New User", team_leader_team_path(@team, :show_user_form => true ) unless @user || @current_user.team != @team %></li>
      </ul>

      <h1 style="text-align: center;"><%= @team.name %></h1>

      <%= render :partial => "team_leader/teams/show_team" unless @user %>

      <% if @user %>
        <h2>New User:</h2><br>
        <%= render :partial => 'team_leader/users/form', :locals => { :user => @user } %>
      <% end %>
      
    </div>
  </div>
</div>